const message = {
   MSG_ADD_TO_CART_SUCCESS: 'MESSAGE ADD TO CART SUCCESS',
   MSG_UPDATE_CART_SUCCESS: 'UPDATE CART SUCCESS',
   MSG_DELETE_PRODUCT_IN_CART_SUCCESS: 'DELETE PRODUCT SUCCESS',
   MSG_CART_EMPTY: 'CART IS EMPTY',
   MSG_WELCOME: 'WELCOME TO SHOPPING ONLINE'
}

export default message
